import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const declarationPath = path.join(rootDir, 'js/src/llama_webgpu_bridge.d.ts');
const declarationText = readFileSync(declarationPath, 'utf8');

function interfaceBody(name) {
  const match = declarationText.match(
    new RegExp(`export interface ${name} \\{\\n([\\s\\S]*?)\\n\\}`),
  );
  assert.ok(match, `interface ${name} not found`);
  return match[1];
}

function members(name) {
  const entries = interfaceBody(name)
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
  return new Map(entries.map((line) => {
    const separator = line.indexOf(':');
    assert.notEqual(separator, -1, `unparsable member in ${name}: ${line}`);
    return [
      line.slice(0, separator).trim(),
      line.slice(separator + 1).replace(/;$/, '').trim(),
    ];
  }));
}

const completionOptions = members('CompletionOptions');
assert.deepEqual(
  [...completionOptions.entries()],
  [
    ['onToken?', '(piece: string | Uint8Array, currentText: string | null) => void'],
    ['signal?', 'AbortSignal'],
    ['warmup?', 'boolean'],
    ['emitCurrentTextOnToken?', 'boolean'],
    ['tokenEventEncoding?', 'TokenEventEncoding'],
    ['tokenEventFlushMs?', 'number'],
    ['tokenEventFlushChars?', 'number'],
    ['nPredict?', 'number'],
    ['mediaMaxPredict?', 'number'],
    ['parts?', 'readonly CompletionMediaPart[]'],
    ['temp?', 'number'],
    ['topK?', 'number'],
    ['topP?', 'number'],
    ['penalty?', 'number'],
    ['grammar?', 'string'],
    ['seed?', 'number'],
  ],
);

assert.deepEqual([...members('EmbedOptions').entries()], [['normalize?', 'boolean']]);

for (const name of ['CompletionOptions', 'EmbedOptions']) {
  assert.doesNotMatch(
    interfaceBody(name),
    /\[key: string\]/,
    `${name} must not declare an index signature`,
  );
}

assert.match(
  interfaceBody('LlamaWebGpuBridgeConfig'),
  /\[key: string\]: unknown;/,
  'LlamaWebGpuBridgeConfig must keep its forward-compatible index signature',
);

const generatedBanner = (source) => (
  `// Generated by scripts/build_js_bridge.mjs from ${source}.\n`
  + '// Do not edit this file directly; update js/src/ and run npm run build:js.\n'
);

const bundledMain = await build({
  entryPoints: [path.join(rootDir, 'js/src/llama_webgpu_bridge.js')],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  minify: false,
  sourcemap: false,
  legalComments: 'none',
  banner: { js: generatedBanner('js/src/llama_webgpu_bridge.js').trimEnd() },
  logLevel: 'silent',
  write: false,
});
assert.equal(bundledMain.outputFiles.length, 1);
assert.equal(
  readFileSync(path.join(rootDir, 'js/llama_webgpu_bridge.js'), 'utf8'),
  bundledMain.outputFiles[0].text,
  'js/llama_webgpu_bridge.js is stale; run npm run build:js',
);

for (const [source, generated] of [
  ['js/src/llama_webgpu_bridge.d.ts', 'js/llama_webgpu_bridge.d.ts'],
  ['js/src/llama_webgpu_bridge_worker.js', 'js/llama_webgpu_bridge_worker.js'],
]) {
  assert.equal(
    readFileSync(path.join(rootDir, generated), 'utf8'),
    generatedBanner(source) + readFileSync(path.join(rootDir, source), 'utf8'),
    `${generated} is stale; run npm run build:js`,
  );
}

const temporaryDir = mkdtempSync(path.join(tmpdir(), 'llama-web-bridge-types-'));
try {
  copyFileSync(declarationPath, path.join(temporaryDir, 'bridge.d.ts'));
  writeFileSync(
    path.join(temporaryDir, 'tsconfig.json'),
    JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        strict: true,
        noEmit: true,
        lib: ['ES2022', 'DOM'],
        types: [],
      },
      include: ['consumer.ts'],
    }),
  );
  writeFileSync(
    path.join(temporaryDir, 'consumer.ts'),
    [
      "import type { CompletionOptions, EmbedOptions } from './bridge.js';",
      '',
      'export const accepted: CompletionOptions = {',
      '  nPredict: 64,',
      '  mediaMaxPredict: 128,',
      "  parts: [{ type: 'image', url: 'a.png' }, { type: 'image', bytes: new DataView(new ArrayBuffer(3)) }, { type: 'audio', samples: new Float32Array(1) }],",
      '  temp: 0.7,',
      '  topK: 40,',
      '  topP: 0.95,',
      '  penalty: 1.1,',
      "  grammar: 'root ::= \"a\"',",
      '  seed: 7,',
      '};',
      '',
      'export const acceptedEmbed: EmbedOptions = { normalize: false };',
      '',
      'export const rejected: CompletionOptions = { temperature: 0.7 };',
      'export const rejectedEmbed: EmbedOptions = { normalise: false };',
      "export const rejectedPart: CompletionOptions = { parts: [{ type: 'video' }] };",
      "export const rejectedArrayLike: CompletionOptions = { parts: [{ type: 'image', bytes: { 0: 255, length: 1 } }] };",
      "export const rejectedImageSource: CompletionOptions = { parts: [{ type: 'image' }] };",
      "export const rejectedAudioSource: CompletionOptions = { parts: [{ type: 'audio' }] };",
      '',
    ].join('\n'),
  );

  const compilation = spawnSync(
    process.execPath,
    [path.join(rootDir, 'node_modules/typescript/bin/tsc'), '-p', '.'],
    { cwd: temporaryDir, encoding: 'utf8' },
  );
  assert.equal(compilation.error, undefined, `failed to run tsc: ${compilation.error}`);
  assert.notEqual(compilation.status, 0, 'tsc unexpectedly accepted every invalid declaration');
  assert.equal(compilation.stderr, '', `tsc unexpectedly emitted stderr:\n${compilation.stderr}`);

  const diagnostics = compilation.stdout;
  const errors = diagnostics.match(/^consumer\.ts\([^\n]+error TS\d+:/gm) || [];
  assert.equal(
    errors.length,
    6,
    `expected exactly six consumer diagnostics:\n${diagnostics}`,
  );
  assert.match(diagnostics, /'temperature' does not exist in type 'CompletionOptions'/);
  assert.match(diagnostics, /'normalise' does not exist in type 'EmbedOptions'/);
  assert.match(diagnostics, /Type '"video"' is not assignable/);
  assert.match(diagnostics, /Type '\{ 0: number; length: number; \}' is not assignable to type 'CompletionMediaData/);
  assert.match(diagnostics, /Type '\{ type: "image"; \}' is not assignable to type 'CompletionMediaPart'/);
  assert.match(diagnostics, /Type '\{ type: "audio"; \}' is not assignable to type 'CompletionMediaPart'/);
} finally {
  rmSync(temporaryDir, { recursive: true, force: true });
}

console.log('Bridge type declaration contract tests passed');
