#!/usr/bin/env node
import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = resolve(root, 'js/src');
const outputDir = resolve(root, 'js');

const mainSource = resolve(sourceDir, 'llama_webgpu_bridge.js');
const mainOutput = resolve(outputDir, 'llama_webgpu_bridge.js');
const workerSource = resolve(sourceDir, 'llama_webgpu_bridge_worker.js');
const workerOutput = resolve(outputDir, 'llama_webgpu_bridge_worker.js');
const declarationSource = resolve(sourceDir, 'llama_webgpu_bridge.d.ts');
const declarationOutput = resolve(outputDir, 'llama_webgpu_bridge.d.ts');

const generatedBanner = (sourcePath) => (
  `// Generated by scripts/build_js_bridge.mjs from ${sourcePath}.\n`
  + '// Do not edit this file directly; update js/src/ and run npm run build:js.\n'
);

await mkdir(outputDir, { recursive: true });

await build({
  entryPoints: [mainSource],
  outfile: mainOutput,
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  minify: false,
  sourcemap: false,
  legalComments: 'none',
  banner: { js: generatedBanner('js/src/llama_webgpu_bridge.js').trimEnd() },
  logLevel: 'info',
});

const workerSourceText = await readFile(workerSource, 'utf8');
await writeFile(
  workerOutput,
  `${generatedBanner('js/src/llama_webgpu_bridge_worker.js')}${workerSourceText}`,
  'utf8',
);
const declarationSourceText = await readFile(declarationSource, 'utf8');
await writeFile(
  declarationOutput,
  `${generatedBanner('js/src/llama_webgpu_bridge.d.ts')}${declarationSourceText}`,
  'utf8',
);
